### ISSUE TITLE
Waardes voor optimizer en loss-function zijn omgewisseld

### ISSUE THREAD

**Issue by milano1110** [hanze-hbo-ict/Machine-Learning#1]
![image](https://github.com/hanze-hbo-ict/Machine-Learning/assets/19352193/d033f9c9-139b-4975-b411-3e12d537be5c)

Optimizer moet 'adam' zijn.
Loss-function moet 'sparse_categorical_crossentropy' zijn.

**Comment by bart314** [comment]
Echt, het aanmaken van dit issue duurt langer dan het oplossen ervan 🤔

**Comment by bart314** [comment]
Opgelost 🍻
